version: "3"

#Docker Reference Architecture: Docker Logging Design and Best Practices
#https://success.docker.com/article/logging-best-practices
#https://docs.docker.com/config/containers/logging/configure/
#https://docs.docker.com/compose/compose-file/#logging
#https://medium.com/@commondream/full-featured-development-logging-with-docker-compose-fluentd-elasticsearch-and-grafana-ce3bec720dd9
#https://docs.docker.com/engine/reference/builder/#onbuild

volumes:
  btc-node_storage: {}
  elastic_storage: {}
  grafana_storage: {}


services:
  #############################################################################
  # Base image
  #############################################################################
  ubuntu18-04:
    build:
      context: ./docker/ubuntu/
      dockerfile: Dockerfile
    image: base-ubuntu:18.04

  #############################################################################
  #Golang project for logging
  #############################################################################
  go-app:
    image: golang:1.11
    #WARNING: no logs are available with the 'fluentd' log driver
    #docker info | grep 'Logging Driver'
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "docker.go.{{.ID}}"
    volumes:
      - ./cmd/:/usr/src/cmd/
    command: go run /usr/src/cmd/main.go

  #############################################################################
  # Bitcoin node for logging
  #############################################################################
  btc-node:
    build:
      context: ./docker/node/btc/
      dockerfile: Dockerfile
    image: btc-watch:0.17
    volumes:
      #- btc-node_storage:/root/.bitcoin
      - ./docker/node/btc/data:/home/hy/.bitcoin
    user: ${UID}:${GID}
    ports:
    - "${RPC_PORT:-19332}:18332"
    stdin_open: true
    tty: true
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "docker.btc-node.{{.ID}}"
    command: /usr/bin/bitcoind --printtoconsole #--conf=/root/.bitcoin/bitcoind.conf
    # docker-compose exec btc-node bash
    # docker-compose exec btc-node bitcoin-cli getnetworkinfo
    # /root/.bitcoin/testnet3/wallets

  #############################################################################
  # monitoring
  #############################################################################

  #Fluentd
  #https://www.fluentd.org/guides/recipes/docker-logging
  #https://docs.docker.com/config/containers/logging/fluentd/
  fluentd:
    build:
      context: ./docker/fluentd/
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  #Elasticsearch
  #https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    #ports:
    #  - 9201:9200
    expose:
      - 9200
      - 9300
    environment:
      - discovery.type=single-node
    volumes:
      - ./docker/elasticsearch/data:/usr/share/elasticsearch/data
      #- elastic_storage:/usr/share/elasticsearch/data

  #Grafana
  #http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later
  grafana:
    image: grafana/grafana:5.4.2
    ports:
      - 3000:3000
    volumes:
      #- ./docker/grafana:/var/lib/grafana
      - grafana_storage:/var/lib/grafana
    depends_on:
      - elasticsearch
